### ISSUE TITLE
Mini media player touch controls out of place

### ISSUE THREAD

**Issue by Jetfly56** [briankrd/Malsp-KUSTOM#1]
The touch targets and the actual location of the objects in the mini media player are not aligned. You can see the location of the media next button marked by the orange frame. 
![Screenshot_20220611-130211_Kustom Lock](https://user-images.githubusercontent.com/47260884/177434482-f1ea804f-0e55-4c86-b4a2-b53618cd818b.jpg)

**Comment by briankrd** [comment]
I have noticed different adaptation problems in different screen sizes, which I am now focusing on beta 3, which I will divide into different builds, thanks for the feedback.
