### ISSUE TITLE
Settings screen doesn't go away when opened

### ISSUE THREAD

**Issue by nathgit** [briankrd/Malsp-KUSTOM#9]
The settings screen opened & closed fine the first time I opened it, but since then it doesn't go away if opened, & has a transparent background. The only way to fix it is to restart KLCK.

**Comment by nathgit** [comment]
I found the close button. It was confusing because of the transparent background.

**Comment by briankrd** [comment]
If it happens again, try applying the preset again, usually the transparent interface problem is due to the engine that KLCK uses to extract the color from the wallpaper.
